title: "Omer Bahadir Eryilmaz"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
collections:
  posts:
    output: true
    permalink: /:collection/:title/
    entries_layout: post
    sort_by: date
    sort_reverse: true
    defaults:
      - scope:  